Add additional dynamic tag

diff --git a/.jenkins/deploy/Jenkinsfile b/.jenkins/deploy/Jenkinsfile
--- a/.jenkins/deploy/Jenkinsfile
+++ b/.jenkins/deploy/Jenkinsfile
@@ -29,47 +29,42 @@ pipeline {
             }
         }
         // Also, check out this way to detect if you are building a tag or not: https://www.youtube.com/watch?v=saiCjlJpfdA
-        stage('Exit early if not buildingTag()') {
-            when {
-                not { buildingTag() }
+        stage('Exit early') {
+             agent any
+             when {
+                not {
+                    anyOf {
+                        buildingTag();
+                        branch 'main';
+                    }
+                }
             }
-            agent any
             steps {
                 script {
-                    echo "Not building a tag. Exiting pipeline with 'NOT_BUILT' status."
+                    echo "Not building tag or main branch. Exiting pipeline with 'NOT_BUILT' status."
                     currentBuild.result = 'NOT_BUILT'
-                    error("Not building a tag. Exiting pipeline with 'NOT_BUILT' status.")
+                    error("Not building tag or main branch. Exiting pipeline with 'NOT_BUILT' status.")
                 }
             }
         }
-        stage('Check if scheduled build is for v1') {
+        stage('Set Dynamic Tag 1') {
             agent any
             steps {
                 script {
-                    def isScheduledBuild = currentBuild.getBuildCauses('hudson.triggers.TimerTrigger$TimerTriggerCause').size() > 0
-                    if (isScheduledBuild && env.TAG_NAME != 'v1') {
-                        echo "Scheduled builds only run for 'v1' tag. Current tag: ${env.TAG_NAME}"
-                        currentBuild.result = 'NOT_BUILT'
-                        error("Exiting pipeline: scheduled builds only run for 'v1' tag.")
+                   // Store whether this is a scheduled build
+                    env.IS_SCHEDULED_BUILD = currentBuild.getBuildCauses('hudson.triggers.TimerTrigger$TimerTriggerCause').size() > 0
+
+                    // Check if we're on main branch
+                    def isMainBranch = env.BRANCH_NAME == 'main'
+
+                    // Set Dynamic Tag 1
+                    // Use 'latest' for main branch, otherwise use tag name
+                    env.DYNAMIC_TAG_1 = isMainBranch ? 'latest' : env.TAG_NAME
+
+                    // Append -nightly for scheduled builds
+                    if (env.IS_SCHEDULED_BUILD == 'true') {
+                        env.DYNAMIC_TAG_1 = "${env.DYNAMIC_TAG_1}-nightly"
                     }
-                }
-            }
-        }
-        stage('Define vars') {
-            agent any
-            steps {
-                script {
-                    def gitUrl = env.GIT_URL
-                    def matcher = gitUrl =~ /https:\/\/github\.com\/([^\/]+)\/([^\/]+)\.git/
-                    if (matcher.matches()) {
-                        env.GITHUB_REPOSITORY_OWNER = matcher[0][1]
-                        env.GITHUB_REPOSITORY_NAME = matcher[0][2]
-                        echo "Owner: ${env.GITHUB_REPOSITORY_OWNER}, Repo: ${env.GITHUB_REPOSITORY_NAME}"
-                    } else {
-                        error "Failed to extract owner and repo from GIT_URL"
-                    }
-                    // Use the Git ref name for the image name
-                    env.GHCR_REPOSITORY = "${env.GITHUB_REPOSITORY_OWNER.toLowerCase()}/${env.GITHUB_REPOSITORY_NAME.toLowerCase()}"
                 }
             }
         }
@@ -94,6 +89,27 @@ pipeline {
                     
                     env.VSCODE_SERVER_COMMIT = response
                     echo "Using VSCode Server Commit: ${env.VSCODE_SERVER_COMMIT}"
+                    // Set Dynamic Tag 2 by appending the commit hash to Dynamic Tag 1
+                    env.DYNAMIC_TAG_2 = "${env.DYNAMIC_TAG_1}-${env.VSCODE_SERVER_COMMIT}"
+                    echo "Dynamic Tag 2: ${env.DYNAMIC_TAG_2}"
+                }
+            }
+        }
+        stage('Define vars') {
+            agent any
+            steps {
+                script {
+                    def gitUrl = env.GIT_URL
+                    def matcher = gitUrl =~ /https:\/\/github\.com\/([^\/]+)\/([^\/]+)\.git/
+                    if (matcher.matches()) {
+                        env.GITHUB_REPOSITORY_OWNER = matcher[0][1]
+                        env.GITHUB_REPOSITORY_NAME = matcher[0][2]
+                        echo "Owner: ${env.GITHUB_REPOSITORY_OWNER}, Repo: ${env.GITHUB_REPOSITORY_NAME}"
+                    } else {
+                        error "Failed to extract owner and repo from GIT_URL"
+                    }
+                    // Use the Git ref name for the image name
+                    env.GHCR_REPOSITORY = "${env.GITHUB_REPOSITORY_OWNER.toLowerCase()}/${env.GITHUB_REPOSITORY_NAME.toLowerCase()}"
                 }
             }
         }
@@ -113,8 +129,11 @@ pipeline {
                                     --label "org.opencontainers.image.source=https://github.com/${GITHUB_REPOSITORY_OWNER}/${GITHUB_REPOSITORY_NAME}" \
                                     --build-arg ARCH=amd64 \
                                     --build-arg VSCODE_SERVER_COMMIT=${VSCODE_SERVER_COMMIT} \
-                                    -t ${GHCR_REGISTRY}/${GHCR_REPOSITORY}:${TAG_NAME}-amd64 .
-                                docker push ${GHCR_REGISTRY}/${GHCR_REPOSITORY}:${TAG_NAME}-amd64
+                                    -t ${GHCR_REGISTRY}/${GHCR_REPOSITORY}:${DYNAMIC_TAG_1}-amd64 \
+                                    -t ${GHCR_REGISTRY}/${GHCR_REPOSITORY}:${DYNAMIC_TAG_2}-amd64 .
+
+                                docker push ${GHCR_REGISTRY}/${GHCR_REPOSITORY}:${DYNAMIC_TAG_1}-amd64
+                                docker push ${GHCR_REGISTRY}/${GHCR_REPOSITORY}:${DYNAMIC_TAG_2}-amd64
                                 '''
                             }
                         }
@@ -134,8 +153,11 @@ pipeline {
                                     --label "org.opencontainers.image.source=https://github.com/${GITHUB_REPOSITORY_OWNER}/${GITHUB_REPOSITORY_NAME}" \
                                     --build-arg ARCH=arm64 \
                                     --build-arg VSCODE_SERVER_COMMIT=${VSCODE_SERVER_COMMIT} \
-                                    -t ${GHCR_REGISTRY}/${GHCR_REPOSITORY}:${TAG_NAME}-arm64 .
-                                docker push ${GHCR_REGISTRY}/${GHCR_REPOSITORY}:${TAG_NAME}-arm64
+                                    -t ${GHCR_REGISTRY}/${GHCR_REPOSITORY}:${DYNAMIC_TAG_1}-arm64 \
+                                    -t ${GHCR_REGISTRY}/${GHCR_REPOSITORY}:${DYNAMIC_TAG_2}-arm64 .
+
+                                docker push ${GHCR_REGISTRY}/${GHCR_REPOSITORY}:${DYNAMIC_TAG_1}-arm64
+                                docker push ${GHCR_REGISTRY}/${GHCR_REPOSITORY}:${DYNAMIC_TAG_2}-arm64
                                 '''
                             }
                         }
@@ -143,7 +165,7 @@ pipeline {
                 }
             }
         }
-        stage('Create and Push Manifest') {
+        stage('Create and Push Manifests') {
             agent { label 'docker' } // Or use any node with Docker CLI
             steps {
                 script {
@@ -152,19 +174,27 @@ pipeline {
                         sh '''
                         echo "${GHCR_PAT}" | docker login ${GHCR_REGISTRY} -u "${GHCR_USER}" --password-stdin
 
-                        docker manifest rm ${GHCR_REGISTRY}/${GHCR_REPOSITORY}:${TAG_NAME} || true
+                        # Create and push manifest for DYNAMIC_TAG_1
+                        docker manifest rm ${GHCR_REGISTRY}/${GHCR_REPOSITORY}:${DYNAMIC_TAG_1} || true
+                        docker manifest create ${GHCR_REGISTRY}/${GHCR_REPOSITORY}:${DYNAMIC_TAG_1} \
+                        ${GHCR_REGISTRY}/${GHCR_REPOSITORY}:${DYNAMIC_TAG_1}-amd64 \
+                        ${GHCR_REGISTRY}/${GHCR_REPOSITORY}:${DYNAMIC_TAG_1}-arm64 --amend
+                        docker manifest annotate ${GHCR_REGISTRY}/${GHCR_REPOSITORY}:${DYNAMIC_TAG_1} \
+                        ${GHCR_REGISTRY}/${GHCR_REPOSITORY}:${DYNAMIC_TAG_1}-amd64 --os linux --arch amd64
+                        docker manifest annotate ${GHCR_REGISTRY}/${GHCR_REPOSITORY}:${DYNAMIC_TAG_1} \
+                        ${GHCR_REGISTRY}/${GHCR_REPOSITORY}:${DYNAMIC_TAG_1}-arm64 --os linux --arch arm64
+                        docker manifest push ${GHCR_REGISTRY}/${GHCR_REPOSITORY}:${DYNAMIC_TAG_1} --purge
 
-                        docker manifest create ${GHCR_REGISTRY}/${GHCR_REPOSITORY}:${TAG_NAME} \
-                            ${GHCR_REGISTRY}/${GHCR_REPOSITORY}:${TAG_NAME}-amd64 \
-                            ${GHCR_REGISTRY}/${GHCR_REPOSITORY}:${TAG_NAME}-arm64 --amend
-
-                        docker manifest annotate ${GHCR_REGISTRY}/${GHCR_REPOSITORY}:${TAG_NAME} \
-                            ${GHCR_REGISTRY}/${GHCR_REPOSITORY}:${TAG_NAME}-amd64 --os linux --arch amd64
-
-                        docker manifest annotate ${GHCR_REGISTRY}/${GHCR_REPOSITORY}:${TAG_NAME} \
-                            ${GHCR_REGISTRY}/${GHCR_REPOSITORY}:${TAG_NAME}-arm64 --os linux --arch arm64
-
-                        docker manifest push ${GHCR_REGISTRY}/${GHCR_REPOSITORY}:${TAG_NAME} --purge
+                        # Create and push manifest for DYNAMIC_TAG_2
+                        docker manifest rm ${GHCR_REGISTRY}/${GHCR_REPOSITORY}:${DYNAMIC_TAG_2} || true
+                        docker manifest create ${GHCR_REGISTRY}/${GHCR_REPOSITORY}:${DYNAMIC_TAG_2} \
+                        ${GHCR_REGISTRY}/${GHCR_REPOSITORY}:${DYNAMIC_TAG_2}-amd64 \
+                        ${GHCR_REGISTRY}/${GHCR_REPOSITORY}:${DYNAMIC_TAG_2}-arm64 --amend
+                        docker manifest annotate ${GHCR_REGISTRY}/${GHCR_REPOSITORY}:${DYNAMIC_TAG_2} \
+                        ${GHCR_REGISTRY}/${GHCR_REPOSITORY}:${DYNAMIC_TAG_2}-amd64 --os linux --arch amd64
+                        docker manifest annotate ${GHCR_REGISTRY}/${GHCR_REPOSITORY}:${DYNAMIC_TAG_2} \
+                        ${GHCR_REGISTRY}/${GHCR_REPOSITORY}:${DYNAMIC_TAG_2}-arm64 --os linux --arch arm64
+                        docker manifest push ${GHCR_REGISTRY}/${GHCR_REPOSITORY}:${DYNAMIC_TAG_2} --purge
                         '''
                     }
                 }
